### ISSUE TITLE
Error  NameError: name 'query_image' is not defined

### ISSUE THREAD

**Issue by Abhijeet241093** [stanleyedward/panorama-image-stitching#2]
(panorama) creapple@creapple-ubuntu:~/Desktop/panorama-image-stitching$ python panorama.py inputs/back_01.jpeg inputs/back_02.jpeg inputs/back_03.jpeg
 ____                                             
|  _ \ __ _ _ __   ___  _ __ __ _ _ __ ___   __ _ 
| |_) / _` | '_ \ / _ \| '__/ _` | '_ ` _ \ / _` |
|  __/ (_| | | | | (_) | | | (_| | | | | | | (_| |
|_|   \__,_|_| |_|\___/|_|  \__,_|_| |_| |_|\__,_|
                                                  

Initializing...
Traceback (most recent call last):
  File "/home/creapple/Desktop/panorama-image-stitching/panorama.py", line 28, in <module>
    main(image_list)
  File "/home/creapple/Desktop/panorama-image-stitching/panorama.py", line 17, in main
    result, mapped_image = recursion.recurse(images_list, no_of_images)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/creapple/Desktop/panorama-image-stitching/image_stitching/recursion.py", line 24, in recurse
    result,_ = utils.forward(
               ^^^^^^^^^^^^^^
  File "/home/creapple/Desktop/panorama-image-stitching/image_stitching/utils.py", line 19, in forward
    image_stitching = ImageStitching(query_photo, train_photo)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/creapple/Desktop/panorama-image-stitching/image_stitching/image_stitching.py", line 10, in __init__
    width_query_photo = query_image.shape[1]
                        ^^^^^^^^^^^
NameError: name 'query_image' is not defined

**Comment by stanleyedward** [comment]
fixed it in 6b7a823614f3ea74c511015aa23e31f08ca48a4a  

thanks for letting me know!
